apiVersion: /v1
kind: Service
metadata:
  name: haproxy-service
  namespace: redis
spec:
  type: ClusterIP
  ports:
    - name: dashboard
      port: 8080
      targetPort: 8080
    - name: redis-write
      port: 6379
      targetPort: 6379
    - name: redis-read
      port: 6380
      targetPort: 6380
  selector:
    app: haproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
  namespace: redis
  labels:
    app: haproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      name: haproxy-pod
      labels:
        app: haproxy
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - haproxy
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: haproxy
          image: registry.digitalocean.com/nsci-image-repo/haproxy:latest
          ports:
            - containerPort: 8080
            - containerPort: 6379
            - containerPort: 6380
      imagePullSecrets:
        - name: nsci-image-repo
      restartPolicy: Always

